version: 2
jobs:
  build:
    environment:
      - _JAVA_OPTIONS: "-Xms512m -Xmx2048m"

    working_directory: ~/DAVe

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute tests & build
          command: mvn -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONARQUBE_TOKEN -DrepoToken=$COVERALLS_TOKEN -B clean verify sonar:sonar coveralls:report

      - run:
          name: Extract test results
          command: |
            mkdir -p target/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} target/junit \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} target/junit \;

      - test-results-store:
          path: target/junit

      - store_artifacts:
          path: target/junit
          destination: tests

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./docker/create_docker.sh
              ./deployment/kube_deploy.sh
            fi
            if [ "${CIRCLE_BRANCH}" == "demo" ]; then
              ./docker/create_docker.sh
              ./deployment/kube_deploy.sh
            fi

