apiVersion: v1
kind: Service
metadata:
  labels:
    name: dave
    project: dave
  name: dave
  namespace: ttsave
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector:
    name: dave
  type: LoadBalancer
