apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ers-deployment
  labels:
    app: amqp
    project: dave
spec:
  replicas: 1
  template:
    metadata:
      name: ers
      labels:
        name: ers
        project: dave
    spec:
      containers:
        - image: ecmi/ers:sim
          name: ers
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 5671
              name: amqps