apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
      volumeID: vol-d371e406
      fsType: ext4
  persistentVolumeReclaimPolicy: Delete