apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: ttsave
  labels:
    app: dave
    layer: frontend
    project: dave
data:
  dave.api: "https://api.ttsave.dave.dbg-devops.com"
  http.compression: "1"