apiVersion: v1
kind: Service
metadata:
  labels:
    app: dave
    layer: frontend
    project: dave
  name: ui
  namespace: ttsave
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: ui
  type: LoadBalancer
